name: RobotFramework Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip3 install robotframework
              pip3 install -U robotframework-tidy
    
          - name: Run linting
            run: |
              robotidy Tests/OPT-WSNOC-1.robot
          
          - name: Commit and push changes
            run: |
              git config --local user.email "husanghost@gmail.com"
              git config --local user.name "HusanboyUs"
              git add Tests/OPT-WSNOC-1.robot
              git commit -m "Linting and formatting changes"
              git push
